name: Trigger AI Edit

on:
  issues:
    types:
      - labeled

jobs:
  ai-edit:
    if: github.event.label.name == 'ai-edit'

    permissions:
      contents: write
      issues: write
      pull-requests: write

    uses: CafeGlow/.GITHUB/.github/workflows/ai-edit.yml@main
    secrets: inherit
